name: JS package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Node.js 10.19.0
      uses: actions/setup-node@v1
      with:
        node-version: 10.19.0
    - name: Install dependencies
      run: npm install
    - name: Lint with eslint
      run: |
        npm run lint
    - name: Unit tests
      run: |
        npm run test
